
author:
    - name: Jeremiah Robert
      email: robertj@vcu.edu

date: 4-29-2025

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
